baseURL = "https://oliviervanaken.com/"
title = "oliviervanaken.com"

enableEmoji = true
enableRobotsTXT = true
languageCode = "en-us"
paginate = 5

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 10

[[menu.main]]
name = "About"
url = "/about/"
weight = 20

[minify]
minifyOutput = true

[module]
[[module.imports]]
path = "github.com/adityatelange/hugo-PaperMod"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
defaultTheme = "auto"
keywords = ["developer", "blog", "page", "cv", "resume"]
ShowCodeCopyButtons = true
ShowBreadCrumbs = true
ShowReadingTime = true
ShowShareButtons = false

[params.profileMode]
enabled = true
title = "Olivier Van Aken"
subtitle = "Senior Developer, Technical Advisor and Mentor"
imageUrl = "https://avatars.githubusercontent.com/u/4215955?v=4"
imageTitle = "Profile picture"
imageWidth = 120
imageHeight = 120

[[params.profileMode.buttons]]
name = "Résumé"
url = "/404"

[[params.socialIcons]]
name = "email"
url = "mailto:olivier@restechnica.io"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/oliviervanaken/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/shiouen"

[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/olivier.va/"

[[params.socialIcons]]
name = "phone"
url = "tel:+32476742003"
