baseURL = 'https://oliviervanaken.com/'
title = 'Olivier Van Aken'

enableRobotsTXT = true
languageCode = 'en-us'

[minify]
minifyOutput = true

[module]
[[module.imports]]
path = 'github.com/adityatelange/hugo-PaperMod'
